config/routes.rb
Rails.application.routes.draw do

  get 'nhl_pool/index'
  get 'nhl_pool/search'
  get '/search', controller: 'nhl_pool', action: 'search'

  resources :leaders
  resources :skaters
  resources :goalies

  resources :pools do
    collection do
      post 'updateSkaters'
    end
    resources :nhl_teams
    resources :pool_members do
      collection do
        post 'addSkater'
        post 'removeSkater'
      end
    end
  end

  root 'nhl_pool#index'

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  has_many :pool_members
  has_many :nhl_teams
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  skip_before_filter :require_pool
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { render :edit }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url }
      format.json { head :no_content }
    end
  end

  def updateSkaters

    @pool = Pool.find(session[:pool_id])

    @skater_response = RestClient.get 'http://www2.tsn.ca/datafiles/JSON/NHL/NHL_STATS_SKATERS.js?c=1'
    @skaterData = @skater_response.split('?')[1].gsub!('[]','{"skater"').gsub!(';','}').gsub!("'",'"')

    @json_skater = ActiveSupport::JSON.decode(@skaterData)

    @json_skater["skater"].each do |skater|
      if skater[22] == 3
        @nhlteamid = NhlTeam.find_by(name: skater[2],pool_id: @pool.id).id

        @upsertSkater = Skater.find_or_create_by(name: skater[1],team: skater[2], nhl_team_id: @nhlteamid) do |s|
          s.name = skater[1]
          s.pos = skater[0]
          s.goals = skater[5]
          s.assists = skater[6]
          s.team = skater[2]
          s.nhl_team_id = @nhlteamid
        end

        @upsertSkater.update(name: skater[1],pos: skater[0],goals: skater[5],assists: skater[6],team: skater[2],nhl_team_id: @nhlteamid)
      end
    end

    @goalie_response = RestClient.get 'http://www2.tsn.ca/datafiles/JSON/NHL/NHL_STATS_GOALIES.js?c=1'
    @goalieData = @goalie_response.split('?')[1].gsub!('[]','{"goalie"').gsub!(';','}').gsub!("'",'"')

    @json_goalie = ActiveSupport::JSON.decode(@goalieData)

    @json_goalie["goalie"].each do |goalie|
      if goalie[24] == 3
        @nhlteamid = NhlTeam.find_by(name: goalie[1],pool_id: @pool.id).id

        @upsertGoalie = Goalie.find_or_create_by(name: goalie[0],team: goalie[1], nhl_team_id: @nhlteamid) do |g|
          g.name = goalie[0]
          g.team = goalie[1]
          g.wins = goalie[10]
          g.so = goalie[8]
          g.goals = goalie[16]
          g.assists = goalie[17]
          g.nhl_team_id = @nhlteamid
        end

        @upsertGoalie.update(name: goalie[0], team: goalie[1], wins: goalie[10],so: goalie[8],goals: goalie[16],assists: goalie[17],nhl_team_id: @nhlteamid)
      end
    end

    @pool_members = Pool.find(session[:pool_id]).pool_members

    @pool_members.each do |member|
      if member.goalie1.present?
        Goalie.where(team: member.goalie1).each do |goalie|
          goalie.update(pool_member_id: member.id)
        end
      end

      if member.goalie2.present?
        Goalie.where(team: member.goalie2).each do |goalie|
          goalie.update(pool_member_id: member.id)
        end

      end
    end

    @pool.update(last_update: Time.now)

    respond_to do |format|
      format.html { redirect_to pools_path, :flash => {:success => "Skater data has been updated" }}
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:name)
    end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_for @pool, :html => { :role => 'form' } do |f| %>

  <div class="form-group">
    <%= f.label :name, :for => :name %>
    <%= f.text_field :name, :class => 'form-control', :placeholder => :name %>
  </div>
  <%= f.submit nil, :class => 'btn btn-default' %>

<% end %>

app/views/pools/edit.html.erb
<div class="row hidden-xs">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading" style="margin-bottom: 10px;">
        <h3>Edit pool</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
      <div class="panel-footer" style="margin-top: 10px;">
        <div class="row">
          <div class="col-md-12">
            <%= link_to 'Show', @pool %> |
            <%= link_to 'Back', pools_path %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pools/index.html.erb
<div class="row hidden-xs">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading" style="margin-bottom: 10px;">
        <h3>Pools</h3>
        <%= link_to '(Add a new Pool)', new_pool_path %>
      </div>

      <table class="table table-striped table-condensed">
        <thead>
        <tr>
          <th>Name</th>
          <th>Last Update</th>
          <th colspan="4"></th>
        </tr>
        </thead>

        <tbody>
        <% @pools.each do |pool| %>
            <tr>
              <td><%= pool.name %></td>
              <td><%= pool.last_update.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y %I:%M %p") %></td>
              <td><%= link_to 'Playoff teams', pool_nhl_teams_path(pool) %></td>
              <td><%= link_to 'Pool Members', pool_pool_members_path(pool) %></td>
              <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
              <td><%= link_to 'Destroy', pool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <div class="panel-footer" style="margin-top: 10px;">
        <div class="row">
          <div class="col-md-12">
            <h5 class="pull-right">
              <strong>Use to refresh stats if schedular doesn't work.</strong>
              <%= link_to "Refresh Player Stats", updateSkaters_pools_path, method: :post, :class => 'btn btn-success' %>
            </h5>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pools/new.html.erb
<div class="row hidden-xs">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading" style="margin-bottom: 10px;">
        <h3>Create a new pool</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
      <div class="panel-footer" style="margin-top: 10px;">
        <div class="row">
          <div class="col-md-12">
            <%= link_to 'Back', pools_path %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pool.name %>
</p>

<%= link_to 'Edit', edit_pool_path(@pool) %> |
<%= link_to 'Back', pools_path %>