config/routes.rb
Rails.application.routes.draw do

  get 'nhl_pool/index'
  get 'nhl_pool/search'
  get '/search', controller: 'nhl_pool', action: 'search'

  resources :leaders
  resources :skaters
  resources :goalies

  resources :pools do
    collection do
      post 'updateSkaters'
    end
    resources :nhl_teams
    resources :pool_members do
      collection do
        post 'addSkater'
        post 'removeSkater'
      end
    end
  end

  root 'nhl_pool#index'

end

app/models/pool_member.rb
class PoolMember < ActiveRecord::Base
  has_many :skaters
  has_many :goalie
  belongs_to :pool

  def total_team_points
    (skaters.sum(:goals)*2) + skaters.sum(:assists) + (goalie.sum(:wins)*2) + (goalie.sum(:so)*3) + (goalie.sum(:goals)*2) + goalie.sum(:assists)
  end

  def total_goals
    skaters.sum(:goals) + goalie.sum(:goals)
  end

  def total_assists
    skaters.sum(:assists) + goalie.sum(:assists)
  end

  def remaining_players
    @remainingSkaters = Skater.joins(:nhl_team).where('nhl_teams.active' => true,'skaters.pool_member_id' => self.id).count

    @team1 = NhlTeam.find_by(name: self.goalie1, pool_id: self.pool.id)
    @team2 = NhlTeam.find_by(name: self.goalie2, pool_id: self.pool.id)

    if(@team1 && @team1.active)
      @remainingSkaters += 1
    end

    if(@team2 && @team2.active)
      @remainingSkaters += 1
    end

    @remainingSkaters
  end

end

app/controllers/pool_members_controller.rb
class PoolMembersController < ApplicationController
  skip_before_filter :require_pool
  before_action :set_pool
  before_action :set_pool_member, only: [:show, :edit, :update, :destroy]

  # GET /pool_members
  # GET /pool_members.json
  def index
    @pool_members = @pool.pool_members
  end

  # GET /pool_members/1
  # GET /pool_members/1.json
  def show
    @skaterNames = Skater.joins(:nhl_team).where('nhl_teams.pool_id' => session[:pool_id]).map{|x| {label: x.name, value: x.id, team: x.team}}
  end

  # GET /pool_members/new
  def new
    @playoff_teams = playoff_teams.map{ |team| [team, team] }
    @pool_member = @pool.pool_members.new
  end

  # GET /pool_members/1/edit
  def edit
    @playoff_teams = playoff_teams.map{ |team| [team, team] }
  end

  # POST /pool_members
  # POST /pool_members.json
  def create
    @pool = Pool.find(params[:pool_id])
    @pool_member = @pool.pool_members.new(pool_member_params)

    respond_to do |format|
      if @pool_member.save
        format.html { redirect_to pool_pool_members_path, notice: 'Pool member was successfully created.' }
        format.json { render :show, status: :created, location: @pool_member }
      else
        format.html { render :new }
        format.json { render json: @pool_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pool_members/1
  # PATCH/PUT /pool_members/1.json
  def update
    respond_to do |format|
      if @pool_member.update(pool_member_params)
        if @pool_member.goalie1.present?
          Goalie.where(team: @pool_member.goalie1).each do |goalie|
            goalie.update(pool_member_id: params[:id])
          end
        end

        if @pool_member.goalie2.present?
          Goalie.where(team: @pool_member.goalie2).each do |goalie|
            goalie.update(pool_member_id: params[:id])
          end
        end

        format.html { redirect_to pool_pool_members_path, notice: 'Pool member was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool_member }
      else
        format.html { render :edit }
        format.json { render json: @pool_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pool_members/1
  # DELETE /pool_members/1.json
  def destroy
    @pool_member.destroy
    respond_to do |format|
      format.html { redirect_to pool_pool_members_url }
      format.json { head :no_content }
    end
  end

  def addSkater
    @pool_member = PoolMember.find(params[:id])
    @skater = Skater.find(params[:nhlId])

    respond_to do |format|
      if @skater.update(pool_member_id: params[:id])
        format.html { redirect_to pool_pool_member_path(params[:pool_id],params[:id]), notice: 'Pool member was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @pool_member }
      end
    end
  end

  def removeSkater
    @pool_member = PoolMember.find(params[:id])
    @skater = Skater.find(params[:skaterId])

    respond_to do |format|
      if @skater.update(pool_member_id: nil)
        format.js {}
      end
    end
  end

  private
    def set_pool
      @pool = Pool.find(params[:pool_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_pool_member
      @pool_member = PoolMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_member_params
      params.require(:pool_member).permit(:name,:goalie1,:goalie2)
    end

    def playoff_teams
      @playoff_teams = ["NONE","DAL","ANA","MTL","TB","DET","BOS","PHI","NYR","CHI","STL","MIN","COL","LA","SJ","PIT","CLB"]
    end
end

app/helpers/pool_members_helper.rb
module PoolMembersHelper
end

app/views/pool_members/_form.html.erb
<%= form_for [@pool, @pool_member]  do |f| %>
  <% if @pool_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool_member.errors.count, "error") %> prohibited this pool_member from being saved:</h2>

      <ul>
      <% @pool_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :goalie1 %><br>
    <%= f.select(:goalie1, options_for_select(@playoff_teams,:goalie1)) %>
  </div>
  <div class="field">
    <%= f.label :goalie2 %><br>
    <%= f.select(:goalie2, options_for_select(@playoff_teams,:goalie2)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pool_members/edit.html.erb
<h1>Editing pool_member</h1>

<%= render 'form' %>

<%= link_to 'Show', pool_pool_members_path %> |
<%= link_to 'Back', pool_pool_members_path %>

app/views/pool_members/index.html.erb
<div class="row hidden-xs">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading" style="margin-bottom: 10px;">
        <h3>Pool Name: <%= @pool.name %></h3>
      </div>

      <table class="table table-striped table-condensed">
        <thead>
        <tr>
          <th>Name</th>
          <th>Goalie 1</th>
          <th>Goalie 2</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @pool_members.each do |pool_member| %>
            <tr>
              <td><%= pool_member.name %></td>
              <td><%= pool_member.goalie1 %></td>
              <td><%= pool_member.goalie2 %></td>
              <td><%= link_to 'Show', pool_pool_member_path(pool_member.pool,pool_member) %></td>
              <td><%= link_to 'Edit', edit_pool_pool_member_path(pool_member.pool,pool_member) %></td>
              <td><%= link_to 'Destroy', pool_pool_member_path(pool_member.pool,pool_member), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <div class="panel-footer" style="margin-top: 10px;">
        <div class="row">
          <div class="col-md-12">
            <%= link_to 'New Pool member', new_pool_pool_member_path %>
            <p class="pull-right">
                <%= link_to 'Back to Pools', pools_path %>
            </p>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pool_members/new.html.erb
<div class="row hidden-xs">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">
  <div class="col-md-10">
    <div class="panel panel-default">
      <div class="panel-heading" style="margin-bottom: 10px;">
        <h3>New pool member for <%= @pool.name %></h3>
      </div>
      <%= render 'form' %>

      <div class="panel-footer" style="margin-top: 10px;">
        <div class="row">
          <div class="col-md-12">
            <p class="pull-right">
              <%= link_to 'Back', pool_pool_members_path %>
            </p>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pool_members/show.html.erb
<p id="notice"><%= notice %></p>

<%= content_tag "div", id: "skaters", data: {url: @skaterNames.to_json} do %>
<% end %>

<p>
  <strong>Pool:</strong>
  <%= @pool_member.pool.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pool_member.name %>
</p>

<h1>Skaters</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Team</th>
    <th>Pos</th>
    <th>Goals</th>
    <th>Assists</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody id="skaterList">
  <%= render @pool_member.skaters %>
  </tbody>
</table>

<%= form_tag("addSkater", method: "post", remote: true) do %>
    <div class="field">
      <%= label_tag :name %><br>
      <%= text_field_tag :skaterSearch %>
      <%= hidden_field_tag :nhlId %>
      <%= hidden_field_tag :pool, @pool_member.pool.id %>
      <%= hidden_field_tag :id, @pool_member.id %>
    </div>
    <%= submit_tag("Add Skater") %>
<% end %>

<h1>Goalies</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Team</th>
    <th>Wins</th>
    <th>Shutouts</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @pool_member.goalie %>
  </tbody>
</table>

<%= link_to 'Edit', edit_pool_pool_member_path(@pool_member.pool,@pool_member) %> |
<%= link_to 'Back', pool_pool_members_path %>