config/routes.rb
Rails.application.routes.draw do

  get 'nhl_pool/index'
  get 'nhl_pool/search'
  get '/search', controller: 'nhl_pool', action: 'search'

  resources :leaders
  resources :skaters
  resources :goalies

  resources :pools do
    collection do
      post 'updateSkaters'
    end
    resources :nhl_teams
    resources :pool_members do
      collection do
        post 'addSkater'
        post 'removeSkater'
      end
    end
  end

  root 'nhl_pool#index'

end

app/models/nhl_team.rb
class NhlTeam < ActiveRecord::Base
  belongs_to :pool
  has_many :skaters
end

app/controllers/nhl_teams_controller.rb
class NhlTeamsController < ApplicationController
  skip_before_filter :require_pool
  before_action :set_pool
  before_action :set_nhl_team, only: [:show, :edit, :update, :destroy]

  # GET /nhl_teams
  # GET /nhl_teams.json
  def index
    @nhl_teams = @pool.nhl_teams
  end

  # GET /nhl_teams/1
  # GET /nhl_teams/1.json
  def show
  end

  # GET /nhl_teams/new
  def new
    @nhl_team = @pool.nhl_teams.new
  end

  # GET /nhl_teams/1/edit
  def edit
  end

  # POST /nhl_teams
  # POST /nhl_teams.json
  def create
    @nhl_team = @pool.nhl_teams.new(nhl_team_params)

    respond_to do |format|
      if @nhl_team.save
        format.html { redirect_to pool_nhl_teams_path, notice: 'Nhl team was successfully created.' }
        format.json { render :show, status: :created, location: @nhl_team }
      else
        format.html { render :new }
        format.json { render json: @nhl_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nhl_teams/1
  # PATCH/PUT /nhl_teams/1.json
  def update
    respond_to do |format|
      if @nhl_team.update(nhl_team_params)
        format.html { redirect_to pool_nhl_teams_path, notice: 'Nhl team was successfully updated.' }
        format.json { render :show, status: :ok, location: @nhl_team }
      else
        format.html { render :edit }
        format.json { render json: @nhl_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nhl_teams/1
  # DELETE /nhl_teams/1.json
  def destroy
    @nhl_team.destroy
    respond_to do |format|
      format.html { redirect_to pool_nhl_teams_url }
      format.json { head :no_content }
    end
  end

  private
    def set_pool
      @pool = Pool.find(params[:pool_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_nhl_team
      @nhl_team = NhlTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nhl_team_params
      params.require(:nhl_team).permit(:name, :references, :active)
    end
end

app/helpers/nhl_teams_helper.rb
module NhlTeamsHelper
end

app/views/nhl_teams/_form.html.erb
<%= form_for [@pool,@nhl_team], :html => { :role => 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :for => :name %>
    <%= f.text_field :name, :class => 'form-control', :placeholder => :name %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :active %> <%= :active %>
    </label>

  </div>

    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pool_nhl_teams_path, :class => 'btn' %>
<% end %>

app/views/nhl_teams/edit.html.erb
<%- model_class = NhlTeam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nhl_teams/index.html.erb
<%- model_class = NhlTeam -%>
<div class="row hidden-xs">
  <div class="col-md-12"><p></p></div>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading" style="margin-bottom: 10px;">
        <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
      </div>

      <table class="table table-striped">
        <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:pool_id) %></th>
          <th><%= model_class.human_attribute_name(:active) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
        </thead>
        <tbody>
        <% @nhl_teams.each do |nhl_team| %>
            <tr>
              <td><%= link_to nhl_team.id, pool_nhl_team_path(nhl_team.pool,nhl_team) %></td>
              <td><%= nhl_team.name %></td>
              <td><%= nhl_team.pool_id %></td>
              <td><%= nhl_team.active %></td>
              <td><%=l nhl_team.created_at %></td>
              <td>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_pool_nhl_team_path(nhl_team.pool,nhl_team), :class => 'btn btn-mini' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            pool_nhl_team_path(nhl_team.pool,nhl_team),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-mini btn-danger' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <div class="panel-footer" style="margin-top: 10px;">
        <div class="row">
          <div class="col-md-12">
            <%= link_to t('.new', :default => t("helpers.links.new")),
                        new_pool_nhl_team_path,
                        :class => 'btn btn-primary' %>
            <div class="pull-right">
              <%= link_to 'Back', pools_path %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/nhl_teams/new.html.erb
<%- model_class = NhlTeam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nhl_teams/show.html.erb
<%- model_class = NhlTeam -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @nhl_team.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pool_id) %>:</strong></dt>
  <dd><%= @nhl_team.pool_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @nhl_team.active %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pool_nhl_teams_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pool_nhl_team_path(@nhl_team.pool,@nhl_team), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pool_nhl_team_path(@nhl_team.pool,@nhl_team),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>