config/routes.rb
Rails.application.routes.draw do

  get 'nhl_pool/index'
  get 'nhl_pool/search'
  get '/search', controller: 'nhl_pool', action: 'search'

  resources :leaders
  resources :skaters
  resources :goalies

  resources :pools do
    collection do
      post 'updateSkaters'
    end
    resources :nhl_teams
    resources :pool_members do
      collection do
        post 'addSkater'
        post 'removeSkater'
      end
    end
  end

  root 'nhl_pool#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "NHL Pool" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= javascript_include_tag "application" %>

  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-50277111-1', 'simplenhlpool.herokuapp.com');
      ga('send', 'pageview');

  </script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">NHL Pool</a>
    </div>
    <div class="collapse navbar-collapse">
      <% if params[:controller] == 'leaders' || params[:controller] == 'skaters' || params[:controller] == 'goalies' %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Leader Board", leaders_path  %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pool Members <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% @pool_members.each do |member| %>
                    <li><%= link_to member.name, leader_path(member)  %></li>
                <% end %>
              </ul>
            </li>
            <li><%= link_to "All Skaters Stats", skaters_path  %></li>
            <li><%= link_to "All Goalie Stats", goalies_path  %></li>
          </ul>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |type, message| %>
          <div class="row">
            <div class="col-md-4" style="padding-top: 10px;">
              <%= content_tag(:div,
                              content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                                      message.html_safe, :class => "alert fade in alert-#{type}") %>
            </div>
          </div>
      <% end %>
    </div><!--/row-->
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
  <footer>
    <p></p>
  </footer>

</div> <!-- /container -->

</body>
</html>